name: Publish nuget package

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x' # SDK Version to use.
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_AUTH_TOKEN}}
      - run: dotnet build --configuration Release FastOptions
      - name: Create the package
        run: dotnet pack --configuration Release FastOptions
      - name: Publish the package to GPR
        run: dotnet nuget push FastOptions/bin/Release/*.nupkg